### ISSUE TITLE
Icon default

### ISSUE THREAD

**Issue by Khybersghost** [eadorin/target-enhancements#1]
Forge-VTT server based game
Windows 10
Chrome
When I target things as the DM, the module works fantastic. When my players target anything, the icon displayed is the generic actor icon. 

Only thing I can see in console is
DevTools failed to load SourceMap: Could not load content for https://asgard.forge-vtt.com/modules/target-enhancements/src/pixi-filters.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

So, not sure if its an error with the mod or something specifically to do with Forge, but I thought I would post here to start.

**Comment by Khybersghost** [comment]
![Targetingerror](https://user-images.githubusercontent.com/65833146/84836595-e5c01400-afea-11ea-9a57-4d218e007efa.png)

**Comment by eadorin** [comment]
This happens when players do not have an avatar configured. To do so, right-click on their name in the "Players" box in the bottom left and select "player configuration".  You can select an avatar in that screen.
