### ISSUE TITLE
About "T" modifier for targeting

### ISSUE THREAD

**Issue by DarKDinDoN** [eadorin/target-enhancements#6]
Hi,

As the GM, when targeting a token with the "T" modifier, the target portrait and the target indicator are shown.
![image](https://user-images.githubusercontent.com/1687854/85222607-d7904000-b3bc-11ea-8d63-a3173068b549.png)

Also, the portrait icon is really dark like there are multiple instances of the same portrait on top of each other.

**Comment by eadorin** [comment]
You were correct...having the event handler in the 'hoverToken' Hook caused it to fire 3 times. It's still showing the wrong icon though so I'm working on that.

**Comment by eadorin** [comment]
This should be resolved now.
