### ISSUE TITLE
Changing the default target indicator

### ISSUE THREAD

**Issue by DarKDinDoN** [eadorin/target-enhancements#7]
Hi,

When not using the default target indicator, changing tool from the left toolbar will replace the selected target indicator with the default one.

Scenario is:
- Go to the configuration and select the BullEyes 1
- As the GM, target a token (showing BullEyes indicator)
- Changing tool in the left toolbar
-> the BullEyes indicator is replaced with the default one

**Comment by eadorin** [comment]
Thanks for pointing this one out, it was tricky! I didn't expect the entire scene to re-render when the controls switch!
